name: Getting-started-usecase

on:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # tag=v0.15.0
        with:
          enable-cache: true

      - name: Setup getting-started usecase
        run: |
          devbox run -- make setup-getting-started

      - name: Verify getting-started usecase
        run: |
          devbox run -- make wait-ready-getting-started-usecase tryout-getting-started-usecase
